fix package license
wmde/WikibaseDataModelTypes pull request #9
Opened 2020-06-09 07:38 UTC by wiese

This is, without doubt, a library "intended for greater external use".
Per the email "Licensing of libraries" (2018-08-30) it is supposed to be
published under Modified-BSD[[0]].

This does not constitute a change of license but fixes a technical
oversight.

[0]: https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_(%22BSD_License_2.0%22,_%22Revised_BSD_License%22,_%22New_BSD_License%22,_or_%22Modified_BSD_License%22)

2020-06-09 07:52 UTC, jakobw requested changes
The change makes sense, but the LICENSE file then needs changing too.

2020-06-09 08:00 UTC, wiese commented
> file then needs changing too.

Love me some redundant bookkeeping. Thanks!

2020-06-09 08:03 UTC, jakobw approved these changes

2020-06-09 08:05 UTC, wiese commented
I'm not sure if all of the individual replacements are 100% in line with what lawyers envisioned, so have those individual commit ids in case this has to be debated.

2020-06-09 08:14 UTC, manicki approved these changes

2020-06-09 10:24 UTC, lucaswerkmeister requested changes
> This does not constitute a change of license but fixes a technical
oversight.

I don’t understand what this is supposed to mean. We published two releases under the old license to npmjs.com – are we now retroactively claiming that they weren’t actually released under that license, and anyone who downloaded them should actually have been aware of our internal license policy instead of trusting the license that we ourselves declared? Do we intend to sue anyone who redistributes the software under the license we declared at the time rather than the license we’re now claiming for those old releases?

The relicense makes sense, but let’s do it without rewriting history.

2020-06-09 16:28 UTC, lucaswerkmeister approved these changes

2020-06-12 10:09 UTC, lucaswerkmeister commented
(I don’t understand why GitHub requires so many local rebases just to make the rebase merge option even available)

2020-06-12 10:09 UTC, merged